---
- name: Config pet node
  hosts: pet
  tasks:
  - name: Copy ansible playbook
    synchronize:
      src: ../cluster_internal
      dest: ~/
      recursive: yes
  - name: Install required packages
    become: yes
    yum:
      name: ansible
      state: latest
  - name: Deploy hosts file
    become: yes
    copy:
      src: ../cluster_internal/files/hosts
      dest: /etc/hosts

