---

- name: Create instances
  hosts: localhost
  tasks:
  - name: create pet instance
    os_server: 
      state: present
      name: "{{ item.name }}"
      image: "{{ image_id }}"
      flavor: "{{ flavor_id }}"
      network: "{{ network_id }}"
      security_groups: "{{ secgroup_id }}"
      floating_ips: "{{ item.ip_float }}"
      key_name: "{{ keyname }}"
    with_items:
      - { name: 'pet', ip_float: [ '89.45.233.23' ] }
    register: pet
  - name: create cattle instances
    os_server: 
      state: present
      name: "{{ item.name }}"
      image: "{{ image_id }}"
      flavor: "{{ flavor_id }}"
      network: "{{ network_id }}"
      security_groups: "{{ secgroup_id }}"
      auto_ip: "{{ item.ip | default('!!null') }}"
      key_name: "{{ keyname }}"
    with_items:
      - { name: 'mon-1', ip: false }
      - { name: 'mon-2', ip: false }
      - { name: 'mon-3', ip: false }
      - { name: 'osd-1', ip: false }
      - { name: 'osd-2', ip: false }
      - { name: 'osd-3', ip: false }
    register: cattle
 
  - name: create hosts file
    lineinfile:
      path: ../files/hosts
      state: present
      create: yes
      regexp: '{{ item.openstack.name }}$'
      line: "{{ item.openstack.private_v4 }}   {{ item.openstack.name }}"
    loop_control:
      label: "{{ item.openstack.name }}"
    with_items:
    - "{{ pet.results }}"
    - "{{ cattle.results }}"

  - name: put pet in ansible inventory file
    lineinfile:
      path: ./inventory
      create: yes
      regexp: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'
      line: "{{ item.openstack.public_v4 }} ansible_connection=ssh ansible_user=centos"
    loop_control:
      label: "{{ item.openstack.name }}"
    with_items:
    - "{{ pet.results }}"

  vars:
    image_id: 679ec412-4c80-4d79-9b70-6f632925b563
    flavor_id: 1493be98-d150-4f69-8154-4d59ea49681c
    network_id: 3db9746e-cdbf-48a6-80c6-a3724145b153
    secgroup_id: c8359c27-ff57-4e27-bf39-cccffbbe6821
    keyname: och
